apiVersion: multitenancy.codereliant.io/v1
kind: Tenant
metadata:
  labels:
    app.kubernetes.io/name: sample-tenant-operator
    app.kubernetes.io/managed-by: kustomize
  name: tenant-sample
spec:
  adminEmail: root@anz.com
  adminGroups:
    - SRE
    - DRE
  userGroups:
    - super-user
  namespaces:
    - sample-ns-1
    - sample-ns-2
