apiVersion: multitenancy.codereliant.io/v1
kind: Tenant
metadata:
  labels:
    app.kubernetes.io/name: sample-tenant-operator
    app.kubernetes.io/managed-by: kustomize
  name: beta-tenant
spec:
  adminEmail: root@admin.com
  adminGroups:
    - SRE
    - DRE
  userGroups:
    - super-user
  namespaces:
    - ns-1
    - ns-2
